### ISSUE TITLE
In the new version v3, how do I use RPC to query? who can  give a curl case?

### ISSUE THREAD

**Issue by debuggor** [vcashorg/vcash-wallet#3]
vcash-wallet all configuration I have not changed.

 curl -0 -XPOST -u grin:a93yefIm4IT7HVVqrqd9 --data '{"jsonrpc":"2.0","method":"retrieve_summary_info","params":[true, 10],"id":1}' http://127.0.0.1:3513/v3/owner

I call this curl and nothing returns

**Comment by jdwldnqi837** [comment]
May be you should check if your api secret and listening port is correct. Here is my sample:curl -0 -XPOST -u grin:your_api_secret --data '{"jsonrpc":"2.0","method":"retrieve_summary_info","params":[true, 10],"id":1}' http://127.0.0.1:your_port/v2/owner

**Comment by debuggor** [comment]
thanks， i got it
